module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: [
    "projects-body",
    "projects-page-wrapper",
    "projects-grid",
    "panel",
    "panel-title",
    "panel-description",
    "panel-meta",
    "meta-right",
    "span-short",
    "span-medium",
    "span-tall",
    "cyber-shift",
    "neural-net",
    "kinetic",
    "quantum",
    "text-cyan",
    "text-red",
    "text-white",
    "modal-overlay",
    "modal-window",
    "modal-close",
    "modal-content",
    "modal-body",
    "active",
  ],
};
